services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"   # Access app at http://localhost:8080
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - "4200:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
      - angular_app_data:/usr/share/nginx/html
    depends_on:
      - angular-app  
volumes:
  angular_app_data:
  
